
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  # Analyze Job (for example, using CodeQL)
  analyze:
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after the 'build' job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CodeQL
        uses: github/codeql-action/setup-codeql@v2
        with:
          languages: javascript, python  # Example: analyzing both JavaScript and Python

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "security"

  # Deploy Job
  deploy:
    runs-on: ubuntu-latest
    needs: analyze  # Deploy after analyze job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: |
          echo "Deploying the app..."

